apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local.opshive.io-crt
  namespace: traefik
spec:
  secretName: local.opshive.io-crt
  isCA: true
  commonName: '*.local.opshive.io'
  dnsNames:
    - local.opshive.io
    - '*.local.opshive.io'
  issuerRef:
    name: local.opshive.io-ca-issuer
    kind: ClusterIssuer
